### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by zhide730** [XchaoWu/Scalable-Neural-Indoor-Scene-Rendering#6]
I run demo.sh on 3090, the GPU takes up 12G, and then prompt oom when the visualization window pops up
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    FASTRENDERING.render_to_screen(FR, FR.WINDOW_W, FR.WINDOW_H, FR.num_group)
  File "/home/user/git-project/Scalable-Neural-Indoor-Scene-Rendering/rendering/scripts/../src/__init__.py", line 238, in render_one_frame
    self.render(**kwargs)
  File "/home/user/anaconda3/envs/snisr/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/git-project/Scalable-Neural-Indoor-Scene-Rendering/rendering/scripts/../src/__init__.py", line 318, in render
    FASTRENDERING.inference_mlp(num_sample_per_step, int(block_starts[-1]), self.num_thread, 
RuntimeError: CUDA error: out of memory
demo.sh: line 2: 41315 Segmentation fault

**Comment by XchaoWu** [comment]
Did you modify any rendering params? Or check your CUDA version & some other environment (I am not sure if this can occur OOM)

**Comment by XchaoWu** [comment]
Did you modify any rendering params? Or check your CUDA version & some other environment (I am not sure if this can cause OOM,  GPU memory of 3090 is enough)
